on:
  push:
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          wget https://github.com/denoland/deno/releases/latest/download/{deno-x86_64-apple-darwin,deno-x86_64-pc-windows-msvc,deno-x86_64-unknown-linux-gnu}.zip
          
          unzip deno-x86_64-apple-darwin.zip
          zip ethereal-x86_64-apple-darwin deno *.ts README.md trace.txt
          rm deno

          unzip deno-x86_64-pc-windows-msvc.zip
          zip ethereal-x86_64-pc-windows-msvc deno.exe *.ts README.md trace.txt

          unzip deno-x86_64-unknown-linux-gnu.zip
          zip ethereal-x86_64-unknown-linux-gnu deno *.ts README.md trace.txt

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          files: |
            ethereal-x86_64-apple-darwin.zip
            ethereal-x86_64-pc-windows-msvc.zip
            ethereal-x86_64-unknown-linux-gnu.zip